#!/usr/bin/env python

import rospy
import os


def main():
	rospy.init_node('hri_node', anonymous=True)
	rate = rospy.Rate(10) # 10hz
	input("Write something to start the task...")
	
	while not rospy.is_shutdown():
		os.system("rosrun groupProject MOVE_LEFT_FLAT_DOWN.py")

		os.system("rosrun groupProject  MOVE_RIGHT_FLAT_DOWN.py")
			
		input("Press something to continue...")
		
		rate.sleep()


if __name__ == '__main__':
	try:
		main()
	except rospy.ROSInterruptException:
		pass
